### ISSUE TITLE
MenuBackgroundColour & MenuFontColour

### ISSUE THREAD

**Issue by spekulatius** [adrexia/silverstripe-brand#2]
Hello Naomi,

thanks for this really useful module :) I noticed the colour definitions for 'MenuBackgroundColour' & 'MenuFontColour' aren't printed out using the brand.ss Did you have css class names in mind for this? Maybe the bootstrap used name 'navbar'? I can open a PR if you want to.

Cheers,
Peter

**Comment by adrexia** [comment]
Sorry, I completely missed this one! 

`MenuBackgroundColour` & `MenuFontColour` are left for devs to implement. This is partly to allow flexibility - I'd like this to work easily with a variety of different FE Frameworks, and defining classes gets in the way of that slightly. I have an example implemented here, for those who prefer to have classes provided:  :) 

https://github.com/adrexia/saga/blob/master/themes/brand/templates/Includes/Styles.ss

**Comment by spekulatius** [comment]
Ah okay. I thought there must be an idea behind it.
